# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/quboqin/multica"
  version "0.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quboqin/multica/releases/download/v0.7.3/multica-cli-0.7.3-darwin-amd64.tar.gz"
      sha256 "46f0a9c6350c83153f809f6744b2fa46e3298f464cc903c3d9e9c1f0848bd159"

      def install
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quboqin/multica/releases/download/v0.7.3/multica-cli-0.7.3-darwin-arm64.tar.gz"
      sha256 "fdb81ccc5918ecb983cbee7db6501ce3a446a276adf2b3db9338a8451114ece3"

      def install
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.3/multica-cli-0.7.3-linux-amd64.tar.gz"
        sha256 "c3c5576bdafb6da0ee23770aa880c978b167eb04d3631e8727467c2d4550988d"

        def install
          bin.install "multica"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.3/multica-cli-0.7.3-linux-arm64.tar.gz"
        sha256 "59eab56df5ffd60280accdb0d2ee4f6a067ff45be128e2fae657d912a4c6942a"

        def install
          bin.install "multica"
        end
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
