# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/quboqin/multica"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quboqin/multica/releases/download/v0.7.1/multica-cli-0.7.1-darwin-amd64.tar.gz"
      sha256 "8092fd32ce38e8965e27c90c05378973bac3c15670053b8e0d209450e502d75b"

      def install
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quboqin/multica/releases/download/v0.7.1/multica-cli-0.7.1-darwin-arm64.tar.gz"
      sha256 "f3e945ad826ae22018ae84a9b8b14d9e6fec301563b71f7bd0bb11c5ea33d7f5"

      def install
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.1/multica-cli-0.7.1-linux-amd64.tar.gz"
        sha256 "c3c2da653fdb5f733ce2532e66612cd9c7804019e50eeb369bdc4bf09c2006a3"

        def install
          bin.install "multica"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.1/multica-cli-0.7.1-linux-arm64.tar.gz"
        sha256 "f7130d82624ff685dba55fe1cc0080951c2b1bc071bae5ad15ee70bf0fbc1bc8"

        def install
          bin.install "multica"
        end
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
