# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/quboqin/multica"
  version "0.7.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quboqin/multica/releases/download/v0.7.2/multica-cli-0.7.2-darwin-amd64.tar.gz"
      sha256 "3009dab5ac779020499f3fbe9c823af758db904cbca5503d846ee7c60fb54449"

      def install
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quboqin/multica/releases/download/v0.7.2/multica-cli-0.7.2-darwin-arm64.tar.gz"
      sha256 "9f940ed50d9360202936dba5222e681786b4475e9896d87b1939946bcd53a4e2"

      def install
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.2/multica-cli-0.7.2-linux-amd64.tar.gz"
        sha256 "657d6c8139ee0e61da4aa31d851cfd6b7c00d864a3b37105e03c647a94cbdc0f"

        def install
          bin.install "multica"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quboqin/multica/releases/download/v0.7.2/multica-cli-0.7.2-linux-arm64.tar.gz"
        sha256 "b774cc092dfed00abce067600ab2ea00ba794d0383f4226e4a95beb60139f6ca"

        def install
          bin.install "multica"
        end
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
